apworld/toontown/__init__.py
toontown/archipelago/packets/clientbound/connected_packet.py
toontown/archipelago/util/win_condition.py
toontown/quest/Quests.py
toontown/toon/DistributedNPCFlippyInToonHall.py
toontown/toon/DistributedNPCFlippyInToonHallAI.py
toontown/toon/DistributedToon.py
toontown/toon/DistributedToonAI.py
toontown/toonbase/ToontownGlobals.py

While doing a run on my own with hood tasks, I discovered a rather embarrassing bug 🥴 it's been fixed with these changes.
Additionally, I added some really helpful text that Flippy uses for the player's objective. It is now possible for players to see what their goal is, which is especially useful if they rolled those options in their YAML.

Fix hood tasks bug, add objective text for Flippy

---

astron/dclass/ttap.dc
toontown/minigame/DistributedMinigame.py
toontown/minigame/DistributedMinigameAI.py
toontown/minigame/DistributedTargetGame.py
toontown/minigame/MinigameRulesPanel.py
toontown/toonbase/TTLocalizerEnglish.py
toontown/toonbase/TTLocalizerEnglishProperty.py

this definitely can be done more elegantly, having the client tell the server to abort the minigame probably isn't the best, although I doubt most people will be on archipelago specifically to play minigames with friends, so it's *probably* fine.
currently trying to figure out how to avoid when skipping toon slingshot, the umbrella stays attached to my toon.

Basic trolley skip button

---

toontown/golf/DistributedGolfHole.py
toontown/golf/GolfGlobals.py

Much faster golfing, but causes the scoreboard to not stay open for very long.
For shots, this is just frameskipping. this shouldn't affect physics, this is just a visual playback - it gets simulated and recorded somewhere else. Will probably look worse on higher numbers, still looked alright at 5, and 5 is ridiculously fast already. The commit sets it to 3 right now. 
For the intro: it's just adjusting the playrate of an animation.
I added globals for the rates to make it easier to change later, if necessary.
This was requested during our run today when a few of us were BKed and went golfing while waiting.

Golf: playback rate implementation.

---

toontown/archipelago/apclient/archipelago_client.py
toontown/archipelago/packets/clientbound/bounced_packet.py
toontown/archipelago/packets/clientbound/connected_packet.py
toontown/archipelago/packets/packet_registry.py
toontown/archipelago/packets/serverbound/connect_update_packet.py

Implements [ConnectUpdate](https://github.com/ArchipelagoMW/Archipelago/blob/main/docs/network%20protocol.md#connectupdate) and now connects without the deathlink tag, followed by adding the tag if the slot has deathlink enabled.

Archipelago: Implement ConnectUpdate packet, Deathlink tag only added when enabled.

---

toontown/archipelago/packets/clientbound/connected_packet.py

Fixes deathlink being entirely broken in the latest version.
with where I placed it, even if it wasn't entirely broken:
only the very first time the toon connects would it use deathlink, otherwise it would just forget entirely. 
edit: force pushing to cleanup a circular reference to `client.av.archipelago_session.client` before this gets merged.

Deathlink: Fix typo and move tag update to proper location.

---

toontown/settings/Settings.py

* swap os and sys calls to using pathlib.Path instead.
* Move creating the directory into the init function
* only try to make the directory if the settings file isn't found.

Settings: Use pathlib.Path for paths, move functionality into init

---

astron/dclass/ttap.dc
toontown/archipelago/packets/clientbound/room_info_packet.py
toontown/toon/DistributedToonAI.py

* Provide feedback to the user when aborting the connection to prevent a reset.
* store archipelago room info's seed_name in the database
Most people play with the same slot name across multiple rooms, so this is just preventing the user from connecting to the wrong room and resetting the toon without any prompt.
depending on how archipelago handles seed_name in it's implementation, this likely can still cause resets connecting between multiple rooms from the same archipelago seed, but running multiple rooms with identical generation at once isn't a very common thing - so it's probably fine to assume two different rooms with the same seed won't be an unintentional reset if it happens.
ideally, eventually we replace "run `~ap reset`" in the dialog with telling the user to click a reset …

Validate room on connect to prevent acidentally resetting toons

---

apworld/EXAMPLE_TOONTOWN.yaml
apworld/toontown/__init__.py
apworld/toontown/options.py
toontown/archipelago/definitions/rewards.py
toontown/toon/DistributedToonAI.py

* gag_training_check_behavior: disabled, to disable checks from training.
* gag_frame_item_behavior: sets whether gags are given directly when you get the frame, instead of needing to train them.
Changes function in game and AP is able to generate.

Gag Training: Add More Options

---

Options.py
apworld/EXAMPLE_TOONTOWN.yaml
apworld/toontown/__init__.py
apworld/toontown/consts.py
apworld/toontown/options.py
apworld/toontown/ruledefs.py
toontown/archipelago/packets/clientbound/connected_packet.py
toontown/archipelago/packets/clientbound/room_info_packet.py
toontown/archipelago/util/win_condition.py
toontown/toon/DistributedNPCFlippyInToonHall.py
toontown/toon/DistributedNPCFlippyInToonHallAI.py
toontown/toon/DistributedToon.py
toontown/toon/DistributedToonAI.py

Allows any number of win conditions, logic was only tested by looking at spoiler logs, but appears fine.
This also refactors most of toontown.archipelago.utils.win_condition while I was already in there doing notable changes to all of it.
Adds OptionGroups to the Options, for the sake of making the WebHost's Game Options page look cleaner.

Multiple Win Conditions and WebHost OptionsGroups.

---

toontown/archipelago/definitions/rewards.py

Solves an issue where gag frames would cause the toon to receive much more experience than necessary to reach the next gag, on both 'vanilla' and 'unlock' gag frame behavior modes.

Gag Training: Correct experience gained when recieving a training frame.

---

toontown/archipelago/apclient/archipelago_client.py
toontown/archipelago/packets/clientbound/data_package_packet.py
toontown/archipelago/packets/clientbound/print_json_packet.py
toontown/archipelago/packets/clientbound/received_items_packet.py
toontown/archipelago/packets/clientbound/room_info_packet.py
toontown/archipelago/util/data_package.py
toontown/archipelago/util/net_utils.py

* Changes datapackage implementation for separating stored packages. raises a warning if calling client.get_item_name with an invalid slot and returning a default value.
* This fixes issues of overlapping IDs causing the wrong name of locations and items being printed - since AP as of 0.5.0 officially allows different games to overlap.
* removed duplicated functions in client with identical functionality, and replaced references accordingly:
* get_item_info in favor of get_item_name
* get_location_info in favor of get_item_name
* Refactored some of the code in ArchipelagoClient (EAFP over LBYL when calls shouldn't fail, move comments about a function's functionality to docstrings)
* Increased max_size on the AP connection to 16MB (matching what AP sets it to, at least as of around 0.4.6 …

Archipelago: Consistency with AP 0.5.0 behavior, small refactor of ArchipelagoClient

---

apworld/EXAMPLE_TOONTOWN.yaml
apworld/toontown/__init__.py
apworld/toontown/items.py

This mostly benefits the web options page, and some of the groups are only useful there, as they only contain one item, but also additionally allows things like `!hint Access Keys` to hint the first access key in logic, regardless of where it's for.
Tested generation with it, and with the changed start hints in the yaml, and it hints all the disguises as expected.
Groups open to change, let me know if there's anything obvious I missed, or if you think something in a group belongs elsewhere.

Archipelago: Add item groups for most items.

---

toontown/settings/Settings.py
toontown/shtiker/OptionsPage.py
toontown/toon/DistributedToon.py
toontown/toonbase/TTLocalizerEnglish.py
toontown/toonbase/ToonBase.py

This pull request introduces a new feature to toggle the overhead Laff Meter display in Toontown. The changes span multiple files to implement this feature, including adding a new setting and updating the relevant UI and behavior.
Key changes include:
* Added a new setting `'laff-display'` to the `Settings` class, defaulting to `True`. (`toontown/settings/Settings.py`)
* Initialized the `laffMeterDisplay` attribute in the `ToonBase` class based on the new setting. (`toontown/toonbase/ToonBase.py`)
* Added `'laff-display'` to the `OptionTypes` and `OptionsTabPage` classes, allowing it to be toggled via a button in the options menu. (`toontown/shtiker/OptionsPage.py`) [[1]](diffhunk://#diff-a56ace02b252e33b0b7e8dbf64f441ee8f6178cb69348f6700122ce71296afedR44) …

Setting: New setting to toggle laff overhead display

---

toontown/discord/DiscordRPC.py

Fixes issue #174
This pull request includes several changes to improve the Discord Rich Presence functionality in the `toontown/discord/DiscordRPC.py` file. The changes primarily focus on handling connection issues more gracefully and ensuring the application can attempt to reconnect if the connection to Discord is lost.
* Added import for `PipeClosed` exception from `pypresence.exceptions` to handle specific pipe closure errors.
* In the `setData` method, added a try-except block to catch `PipeClosed` and `BrokenPipeError` exceptions. If an exception is caught, the method schedules a task to attempt reconnection to Discord after 30 seconds.
* Added a new method `reconnectDiscord` to handle the reconnection logic. This method is called by the scheduled task when a connection error occurs. …

DiscordRPC: Fix bug where discord would crash the game if you close it

---

apworld/EXAMPLE_TOONTOWN.yaml
apworld/toontown/__init__.py
apworld/toontown/items.py
apworld/toontown/locations.py
toontown/archipelago/packets/clientbound/connected_packet.py
toontown/archipelago/packets/clientbound/received_items_packet.py
toontown/archipelago/util/win_condition.py
toontown/shtiker/CheckPage.py
toontown/shtiker/LocationPage.py
toontown/suit/DistributedBossbotBossAI.py
toontown/suit/DistributedCashbotBossAI.py
toontown/suit/DistributedLawbotBossAI.py
toontown/suit/DistributedSellbotBossAI.py
toontown/toon/DistributedToon.py
toontown/toon/DistributedToonAI.py

Fixes a few issues with win conditions in the current release:
* Hood tasks currently let you goal with just completing one playground.
* Cog Bosses don't sync like every other win condition does (now checks if AP locations have been checked)
* ~~Ensures a single boss reward exists if the win condition has bosses as a requirement, and excludes it from logic if it needs to add one for this.~~
* redoes the logic in task goals to avoid converting the toon's full checked locations list into a set every time the win condition is checked, instead creating a class variable containing the goal's locations and using that to compare.
All of them aren't tested all the way to being able to goal, Hood Tasks saw tasks being completed at any rate, it correctly skips ttc when listing tasks left on a toon …

Win condition, Performance and Tracker improvements.

---

requirements.txt

* Avoid breaking changes now and in future builds.
Fixes #182 and avoids the issue returning in the future from any of our modules.

Pin requirements.txt versions.

---

astron/dclass/ttap.dc
toontown/building/DistributedKnockKnockDoor.py
toontown/building/DistributedKnockKnockDoorAI.py

This pull request introduces a few changes to the `DistributedKnockKnockDoor` class and its associated AI class to add a cooldown mechanism and a healing feature for toons. The most important changes include adding new methods to manage cooldowns, modifying the interaction logic to include healing, and cleaning up unused methods.
Enhancements to `DistributedKnockKnockDoor`:
* Added a `cooldown` attribute and methods `setCooldown` and `resetCooldown` to manage cooldown periods for interactions. [[1]](diffhunk://#diff-9acec79654f1a1aec74b30669137c121dad8d4e85e0f96649e47b3990433f84eL13-R21) [[2]](diffhunk://#diff-9acec79654f1a1aec74b30669137c121dad8d4e85e0f96649e47b3990433f84eR58-R66)
* Updated the `knockKnockTrack` method to include calls to `healToon` and `setCooldown` to heal avatars and …

KnockKnockDoor: Heal a toon when hearing a knock knock joke

---

Options.py
apworld/EXAMPLE_TOONTOWN.yaml
apworld/toontown/__init__.py
apworld/toontown/consts.py
apworld/toontown/options.py
apworld/toontown/ruledefs.py

- Additionally, convert win condition to a list, rather than separate options. this might make specific randomized conditions more difficult without using triggers.
- Updates the two above options when randomizing for the purpose of displaying to the spoiler log.
NOTE: breaking change for yamls, existing yamls will not function with this change. merge this with a version increase for clarity. (0.15)
to preserve existing yamls, changing randomized gags to have two randomized entries, and changing any win_condition_x to web_win_condition_x will have the current functionality - recommend swapping to the new win_conditions entry however for win conditions if possible.

apworld: change functionality of 'randomized' in gags and win conditions

---

otp/ai/AIMsgTypes.py
otp/level/DistributedLevel.py
otp/level/LevelSpec.py
otp/uberdog/OtpAvatarManager.py
toontown/ai/ToontownAIMsgTypes.py
toontown/battle/BattleEffectHandlersAI.py
toontown/estate/DistributedCannon.py
toontown/estate/houseDesign.py
toontown/hood/ZeroAnimatedProp.py
toontown/minigame/DistributedCannonGame.py
toontown/parties/DistributedPartyCannonActivity.py
toontown/quest/QuestParser.py

This PR replaces many known unsafe functions in Toontown's code (i.e: `eval`, `exec`, `pickle`) with safer alternatives.
This is for security reasons; if an exploit is potentially found that takes advantage of these functions, arbitrary code could theoretically be executed   
As of now, the remaining code that have these unsafe functions (excluding the dev injector) are in `otp/chat` and `toontown/chat` (apparently TTO devs had the ability to execute code via chat), the Cog HQ in game editor, and scavenger hunt related code.
For the TTO-era chat eval/exec code, I propose removing this functionality from TTAP. It's a potential security nightmare to keep and there are better alternatives for executing code at dev runtime.
The scavenger hunt code (especially the DataStore classes) could be …

general: Replace unsafe functions.

---

astron/dclass/ttap.dc
toontown/suit/DistributedBossCog.py
toontown/suit/DistributedLawbotBossAI.py
toontown/suit/DistributedSellbotBossAI.py

This is for accessibility purposes.
And also so people can play with sound off

DistributedBossCog: Show an ! above the toon's head when a boss jumps

---

apworld/toontown/options.py

apworld fix: `web_win_conditions_randomized` was not visible in the web ui, and was being shown in the spoiler log and the generated template instead.

bugfix: correct visibility and class of web option

---

apworld/toontown/__init__.py

solves `AssertionError: x is not y` when adding multiples of the same item instance.
this errors consistently when running AP from source, but when genning from the client couldn't be reproduced due to `assert` statements being optmized out of compiled builds.
requested this to be tested with the fuzzer, result was 7 out of 100 gens erroring, all due to FillErrors, which is more what was expected.

Fixes AssertionErrors when running AP from source.

---

toontown/archipelago/apclient/archipelago_client.py
toontown/archipelago/apclient/archipelago_session.py
toontown/archipelago/packets/clientbound/connected_packet.py

Fixes disconnect when connecting to multiworlds where for some reason any pet shop or task location did not get an item (and therefore is not part of the multiworld) - most likely caused by bugs in other apworlds (not enough items to fill all locations)
prints a few debug messages onto screen whenever we attempt to scout one of such locations. (on connect, and again when you talk to the npcs in particular)

bugfix: Don't ask AP for non-existent locations

---

toontown/settings/Settings.py

Typically wouldn't be needed, but this would prevent a potential crash in the future if we add a new control and someone plays a previous version

Settings: Prevent crash if control doesn't exist
